name: VM Resource Monitor

on:
  # Allows manual trigger testing from the Github UI
  workflow_dispatch:

jobs:
  check-vm-resources:
    # Forces the workflow exectution inside the VPN-protected VM
    runs-on: self-hosted

    steps:
    - name: Checkout Local Repository Context
      uses: actions/checkout@v4

      # Since this is a self-hosted runner, Python, psutil, and pynvml are 
      # already installed on host system. The step below ensures they are ready
    - name: Verify Environment Dependencies
      run: |
        python3 -m pip install --user --upgrade pip
        python3 -m pip install --user psutil nvidia-ml-py requests

    - name: Run Telemetry Audit
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        THRESHOLD_GPU_UTIL: 5.0
        THRESHOLD_GPU_MEM: 5.0
        THRESHOLD_CPU: 5.0
        THRESHOLD_RAM: 5.0
      run: python3 check_metrics.py